server:
  host: localhost
  port: ${server.port}

spring:
  datasource:
    url: ${Spring.datasource.url}
    username: ${Spring.datasource.username}
    password: ${Spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: ${redis.port}
      password: ${redis.password}
      database: ${redis.database}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

oss:
  endpoint: ${oss.endpoint}
  access-key-id: ${oss.access-key-id}
  access-key-secret: ${oss.access-key-secret}
  bucket-name: ${oss.bucket-name}

github:
  api: ${github.api}
  token: ${github.token}